### PR TITLE
Don't fail if pandoc is not installed

### LINKED ISSUE #2: Don't fail with critical error if pandoc is not available
This is a problem where the user is running setup.py as part of a continuous-integration build process where pandoc isn't easily installable (for instance, on travis-ci's container based infrastructure). In that case, just fail with a warning and don't block the rest of the install process.

### PR DESCRIPTION
**Pull request by msabramo**
Closes #2 

@smspillaz: Does this fix the problem for you?

### CODE REVIEW

**Comment by smspillaz** [comment]
I wouldn't be able to check right now, but if I remember correctly the problem was that even `import`ing `pandoc` would raise an exception.

Interestingly enough, I never actually submitted a PR for the fix I've been using, which is here: https://github.com/smspillaz/setuptools-markdown/commit/c137f991394f63fae6c76586fbfd5cfa85f4dbb8

**Comment by smspillaz** [comment]
@msabramo This would fix the problem for me. Can you roll a new release with this fix? My CI is currently blocked on it.

**Comment by msabramo** [comment]
Sorry for the delay. I'll take a look soon.

**Comment by smspillaz** [comment]
Thanks :)

On Sat, May 9, 2015 at 9:14 AM, Marc Abramowitz <notifications@github.com>
wrote:

> Merged #4 <https://github.com/msabramo/setuptools-markdown/pull/4>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msabramo/setuptools-markdown/pull/4#event-300737052>.
>



-- 
Sam Spilsbury

**Comment by msabramo** [comment]
No problem. I'll do a PyPI release a bit later. You can remind me if I forget. 

-Marc
http://marc-abramowitz.com

**Comment by msabramo** [comment]
Released 0.2 with this fix.

https://pypi.python.org/pypi/setuptools-markdown/0.2

**Pull request merged**
